package test.java.modules.users;

public enum Roles {
	NONE,
	ADMIN,
	INTERMEDIATE_TRAFFIC_DEVELOPER,
	MIT_DEVELOPER,
	MYSPORTS_CLOUD_DEVELOPER,
	NAVKIT_DEVELOPER,
	NAVKIT_INTEGRATOR,
	NDS_MAP_UPDATES_DEVELOPER,
	PRODUCTION_USERS,
	CAMERA_MEDIA_SERVER_DEVELOPER,
	CUSTOMER_SERVICE_ROLE
}
